### PR TITLE
Update test.md

### PR DESCRIPTION
**Pull request by kunaaljain**
come message

### CODE REVIEW

**Comment by yangl1996** [comment]
[Issue #49](https://pagure.io/docs-test/issue/49) created on Pagure.

**Comment by kunaaljain** [comment]
hi

**Comment by yangl1996** [comment]
_Commented by Kunaal Jain (kunaaljain)_

```
hello
```

**Comment by yangl1996** [comment]
_Commented by Kunaal Jain (kunaaljain)_

```
some message
```

**Comment by kunaaljain** [comment]
thanks

**Pull request merged**
